In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/shl-datacard/train_cleaned.csv
/kaggle/input/shl-datacard/test_cleaned.csv
/kaggle/input/shl-intern-hiring-assessment/Dataset/sample_submission.csv
/kaggle/input/shl-intern-hiring-assessment/Dataset/train.csv
/kaggle/input/shl-intern-hiring-assessment/Dataset/test.csv
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_885.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1142.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1006.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_817.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_765.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_508.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_257.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_330.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_72.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_328.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_858.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_464.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_505.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_853.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1001.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_855.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_995.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_472.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1028.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_550.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_841.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_256.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_641.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1131.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_234.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_284.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_188.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1220.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_67.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_818.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_967.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_709.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_872.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1165.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_415.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_714.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1231.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_430.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_27.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1207.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_922.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_976.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1180.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_327.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1212.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1092.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1270.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1163.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1041.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_940.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_563.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_661.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_220.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_57.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1136.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1179.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_41.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_590.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1294.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_161.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1069.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_261.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1246.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_89.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_952.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_846.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_909.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1088.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_989.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_865.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_278.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1300.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_298.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_178.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_674.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1104.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_966.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1134.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1079.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1329.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_542.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_954.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_171.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_530.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_822.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_14.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_689.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_309.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1046.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_502.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_568.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_80.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_13.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_668.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1170.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_47.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_218.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1316.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_904.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_268.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_130.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_273.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_962.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1226.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_452.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_585.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1286.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_692.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_357.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_335.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_681.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1186.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_766.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_686.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1099.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_339.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_534.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_531.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1326.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_397.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1218.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_453.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_670.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1090.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1102.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_24.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_978.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_746.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1158.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_682.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_324.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_358.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_377.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_744.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_249.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_956.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_854.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_981.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_245.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_903.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_749.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_929.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_529.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_828.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_236.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_200.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_935.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1200.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_353.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1055.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1255.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_501.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_947.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1217.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_804.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_168.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_701.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_117.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_780.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1059.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_390.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_599.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_153.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_988.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_241.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_481.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_652.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_483.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_787.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1291.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1258.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1039.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_902.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_373.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1138.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1025.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_647.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1225.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1011.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_108.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_34.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_938.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_376.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_769.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_554.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_407.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_99.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_449.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_548.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_664.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_33.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_248.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_774.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_827.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_748.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_301.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_128.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_637.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_267.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_915.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1166.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_450.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_612.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test/audio_1187.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_698.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1176.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_77.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1215.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_66.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_894.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_54.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1232.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_694.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_237.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1032.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_688.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_752.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_596.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_638.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_886.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_711.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_741.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_936.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_538.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1271.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_859.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_845.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_821.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_164.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1266.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1005.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1036.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_994.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_760.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_315.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1284.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1152.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_843.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_25.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_950.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1199.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_753.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1322.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1224.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_7.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1100.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1157.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_406.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_321.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_20.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_59.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_802.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_518.wav
/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train/audio_1310.wav

In [38]:
!pip install -q transformers datasets torchaudio

import os
import torch
import torchaudio
import numpy as np
import pandas as pd

In [40]:
# Dataset Loading


train_df = pd.read_csv("/kaggle/input/shl-datacard/train_cleaned.csv")  
AUDIO_DIR = "/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train"

In [41]:
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import torchaudio
import numpy as np
import pandas as pd
from transformers import BertTokenizer, BertForSequenceClassification, TrainingArguments, Trainer
from transformers import Wav2Vec2Processor, Wav2Vec2Model
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from scipy.stats import pearsonr

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #GPU

In [42]:
#Bert Model

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased").to(device)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [46]:
#For Audio_path

train_df['audio_path'] = train_df['filename'].apply(lambda x: os.path.join(AUDIO_DIR, x))

texts = train_df['filename'].tolist()     
audio_paths = train_df['audio_path'].tolist()
labels = train_df['label'].tolist()

In [47]:


missing_files = []
for path in train_df['audio_path']:
    if not os.path.isfile(path):
        missing_files.append(path)

print(f"Missing files: {missing_files}")

Missing files: []

In [48]:
train_df.head()

,filename,label,transcript,clean_transcript,audio_path
0,audio_710.wav,1.0,sardbraadesh நீ깨 அது என்று தெல்லுது இங்கோடுத்...,sardbraadesh நீ깨 அது என்று தெல்லுது இங்கோடுத்த...,/kaggle/input/shl-intern-hiring-assessment/Dat...
1,audio_1265.wav,1.0,My favorite hobby is cultivation of plants su...,my favorite hobby is cultivation of plants suc...,/kaggle/input/shl-intern-hiring-assessment/Dat...
2,audio_1114.wav,1.5,My Girl is to become an electrical employee ....,my girl is to become an electrical employee. a...,/kaggle/input/shl-intern-hiring-assessment/Dat...
3,audio_946.wav,1.5,the playground looks like very clear and neat...,the playground looks very clear and neat as th...,/kaggle/input/shl-intern-hiring-assessment/Dat...
4,audio_1127.wav,2.0,My goal is to bring my parents to live with m...,my goal is to bring my parents to live with me...,/kaggle/input/shl-intern-hiring-assessment/Dat...

In [50]:


NUM_FOLDS = 5
TEXT_COL = "clean_transcript"
LABEL_COL = "label"
MAX_LEN = 195

# Datset Class for Bert model
class RegressionDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=MAX_LEN):
        self.texts = texts.tolist()
        self.labels = labels.tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, i):
        enc = self.tokenizer(
            self.texts[i],
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels": torch.tensor(self.labels[i], dtype=torch.float),
        }

# Evaluation functions(MAE & Pearson)
def compute_metrics(eval_pred):
    preds, labels = eval_pred
    preds = preds.flatten()
    mae = mean_absolute_error(labels, preds)
    
    pearson_corr = pearsonr(labels, preds)[0]
    return {"mae": mae, "pearson": pearson_corr}


kf = KFold(n_splits=NUM_FOLDS, shuffle=True, random_state=42)

all_mae,  all_pearson = [], []

for fold, (train_idx, val_idx) in enumerate(kf.split(train_df)):
    print(f"\n===== Fold {fold + 1}/{NUM_FOLDS} =====")

    train_texts = train_df.iloc[train_idx][TEXT_COL]
    train_labels = train_df.iloc[train_idx][LABEL_COL]
    val_texts = train_df.iloc[val_idx][TEXT_COL]
    val_labels = train_df.iloc[val_idx][LABEL_COL]

    train_ds = RegressionDataset(train_texts, train_labels, tokenizer)
    val_ds = RegressionDataset(val_texts, val_labels, tokenizer)

    model = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased", num_labels=1                         # Bert Model with a regression head
    ).to(device)

    args = TrainingArguments(
        output_dir=f"./bert_regressor_fold_{fold}",
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        num_train_epochs=9,
        weight_decay=0.01,
        logging_steps=50,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics,
    )

    trainer.train()
   
    trainer.save_model(f"./saved_model_fold_{fold}")  

  
    preds_output = trainer.predict(val_ds)
    preds = preds_output.predictions.flatten()
    true = val_labels.values
    mae = mean_absolute_error(true, preds)
    pearson_corr = pearsonr(true, preds)[0]

    print(f"Fold {fold + 1} - MAE: {mae:.4f}, Pearson: {pearson_corr:.4f}")

    all_mae.append(mae)
  
    all_pearson.append(pearson_corr)

# Final aggregated metrics
print("\n==== Cross-Validation Results ====")
print(f"Avg MAE:     {np.mean(all_mae):.4f} ± {np.std(all_mae):.4f}")

print(f"Avg Pearson: {np.mean(all_pearson):.4f} ± {np.std(all_pearson):.4f}")

===== Fold 1/5 =====

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 1 - MAE: 0.5951, Pearson: 0.6806

===== Fold 2/5 =====

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 2 - MAE: 0.5493, Pearson: 0.7118

===== Fold 3/5 =====

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 4 - MAE: 0.6984, Pearson: 0.5740

===== Fold 5/5 =====

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

Fold 5 - MAE: 0.6402, Pearson: 0.6000

==== Cross-Validation Results ====
Avg MAE:     0.6180 ± 0.0496
Avg Pearson: 0.6245 ± 0.0609

In [51]:

# BERT Embedding Extraction

def extract_bert_embeddings(model, dataset, batch_size=32):
    model.eval()
    dataloader = DataLoader(dataset, batch_size=batch_size)
    embeddings = []

    with torch.no_grad():
        for batch in dataloader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            outputs = model.bert(input_ids=input_ids, attention_mask=attention_mask)
            cls_embeddings = outputs.last_hidden_state[:, 0, :]  # CLS token

            embeddings.append(cls_embeddings.cpu())

    embeddings = torch.cat(embeddings, dim=0)
    return embeddings.numpy()

In [52]:
best_fold = 2 # Best Model Loading


best_model_path = f"./saved_model_fold_{best_fold}"
fine_tuned_model = BertForSequenceClassification.from_pretrained(best_model_path, num_labels=1).to(device)

In [83]:
test_df = pd.read_csv("/kaggle/input/shl-datacard/test_cleaned.csv")

In [93]:
test_texts = test_df[TEXT_COL].fillna("").astype(str).tolist()

In [85]:
Train_texts = train_df[TEXT_COL]
Train_labels = train_df[LABEL_COL]

Test_texts = test_df[TEXT_COL]

In [109]:
Test_texts.isnull().sum()

4

In [110]:
Test_texts = Test_texts.fillna("Missing text")

In [112]:
Test_texts.isnull().sum()

0

In [102]:
Test_texts

0      my hobbies are playing cricket because i am a ...
1      my favorite place is in andhra padesh. it is i...
2      yeah, my best days in my life is recently i go...
3      actually the most i use it to enjoy is practic...
4      i would to become a beauty unit. among the art...
                             ...
199    my favorite hobby is betting on nba and footba...
200    my favorite place to travel is to ocean city, ...
201    the journey to switzerland is an adventure in ...
202    , my goal in life is to live a happy fulfillin...
203    the school playground looks pretty big. there ...
Name: clean_transcript, Length: 204, dtype: object

In [68]:
train_DF=RegressionDataset(Train_texts, Train_labels, tokenizer) #Training Dataset class

In [113]:
test_texts = Test_texts.tolist()  
dummy_labels = np.zeros(len(test_texts))




test_dataset = RegressionDataset(Test_texts, dummy_labels, tokenizer) #Test Dataset Class

In [114]:
test_bert_embeds = extract_bert_embeddings(fine_tuned_model, test_dataset)

In [126]:
test_bert_embeds.shape

(204, 768)

In [69]:
bert_embeds = extract_bert_embeddings(fine_tuned_model, train_DF )

In [70]:
bert_embeds.shape

(424, 768)

In [54]:
!pip install transformers torchaudio

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.51.1)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.11/dist-packages (2.5.1+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.30.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: torch==2.5.1 in /usr/local/lib/python3.11/dist-packages (from torchaudio) (2.5.1+cu124)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (2024.12.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch==2.5.1->torchaudio) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch==2.5.1->torchaudio) (1.3.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.5.1->torchaudio) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2022.1.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.17->transformers) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.17->transformers) (2024.2.0)

In [55]:
from transformers import Wav2Vec2Model, Wav2Vec2Processor # For Audio Embeddings
import torchaudio


wav2vec_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h").to(device)
wav2vec_processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")

Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [56]:
#preprocessing the audio files (like sampling, trimming silence, normlaisation,etc.)


import librosa
import soundfile as sf
import os
from tqdm import tqdm

def preprocess_audio(input_path, output_path, target_sr=16000):
   
    y, sr = librosa.load(input_path, sr=None)

  
    y_resampled = librosa.resample(y, orig_sr=sr, target_sr=target_sr)

    
    y_trimmed, _ = librosa.effects.trim(y_resampled, top_db=20)

    
    y_normalized = librosa.util.normalize(y_trimmed)

    
    sf.write(output_path, y_normalized, target_sr)


def batch_preprocess(input_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    for file in tqdm(os.listdir(input_dir)):
        if file.endswith(".wav"):
            preprocess_audio(
                input_path=os.path.join(input_dir, file),
                output_path=os.path.join(output_dir, file)
            )


batch_preprocess("/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/train", "processed_audio/train/")
batch_preprocess("/kaggle/input/shl-intern-hiring-assessment/Dataset/audios/test", "processed_audio/test/")

100%|██████████| 444/444 [03:05<00:00,  2.40it/s]
100%|██████████| 204/204 [01:17<00:00,  2.62it/s]

In [71]:
#Audio Embedding Extraction

def extract_audio_embedding(audio_path, model, processor, device):
   
    waveform, sample_rate = torchaudio.load(audio_path)
    
   
    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0).unsqueeze(0)

   
    if sample_rate != 16000:
        resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=16000)
        waveform = resampler(waveform)
        sample_rate = 16000

    inputs = processor(waveform.squeeze(0), sampling_rate=sample_rate, return_tensors="pt", padding=True)

    with torch.no_grad():
        outputs = model(inputs.input_values.to(device))

  
    embeddings = outputs.last_hidden_state.mean(dim=1)  

    return embeddings.squeeze(0).cpu().numpy()

In [127]:
train_audio_folder= "/kaggle/working/processed_audio/train"

audio_embeddings = []

for fname in train_df['filename']:
    audio_path = os.path.join(train_audio_folder, fname)
    emb = extract_audio_embedding(audio_path, wav2vec_model, wav2vec_processor, device)
    audio_embeddings.append(emb)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [76]:
audio_embeddings = np.vstack(audio_embeddings)

In [77]:
audio_embeddings.shape

(424, 768)

In [79]:
X_train = np.concatenate([bert_embeds, audio_embeddings], axis=1) #Concatenating Bert+audio embeddings for XGB.
Y_train = Train_labels.values    #Ground Truth Levels.

In [90]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Data Splitting
X_tr, X_val, y_tr, y_val = train_test_split(X_train, Y_train, test_size=0.1, random_state=42)


xgb_model = xgb.XGBRegressor(
    objective='reg:squarederror',
    eval_metric='rmse',
    learning_rate=0.01,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    seed=42,
    tree_method='gpu_hist',  
)


xgb_model.fit(X_tr, y_tr, eval_set=[(X_tr, y_tr), (X_val, y_val)], early_stopping_rounds=50, verbose=True)

[0]	validation_0-rmse:1.04694	validation_1-rmse:1.02692
[1]	validation_0-rmse:1.03829	validation_1-rmse:1.01890
[2]	validation_0-rmse:1.02961	validation_1-rmse:1.01044

/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [06:43:10] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

[3]	validation_0-rmse:1.02165	validation_1-rmse:1.00267
[4]	validation_0-rmse:1.01321	validation_1-rmse:0.99540
[5]	validation_0-rmse:1.00522	validation_1-rmse:0.98778
[6]	validation_0-rmse:0.99705	validation_1-rmse:0.98247
[7]	validation_0-rmse:0.98900	validation_1-rmse:0.97633
[8]	validation_0-rmse:0.98137	validation_1-rmse:0.96948
[9]	validation_0-rmse:0.97340	validation_1-rmse:0.96113
[10]	validation_0-rmse:0.96579	validation_1-rmse:0.95528
[11]	validation_0-rmse:0.95809	validation_1-rmse:0.94870
[12]	validation_0-rmse:0.95019	validation_1-rmse:0.94459
[13]	validation_0-rmse:0.94265	validation_1-rmse:0.93696
[14]	validation_0-rmse:0.93515	validation_1-rmse:0.93171
[15]	validation_0-rmse:0.92753	validation_1-rmse:0.92315
[16]	validation_0-rmse:0.92022	validation_1-rmse:0.91623
[17]	validation_0-rmse:0.91290	validation_1-rmse:0.90972
[18]	validation_0-rmse:0.90579	validation_1-rmse:0.90216
[19]	validation_0-rmse:0.89865	validation_1-rmse:0.89662
[20]	validation_0-rmse:0.89148	validation_1-rmse:0.89047
[21]	validation_0-rmse:0.88449	validation_1-rmse:0.88311
[22]	validation_0-rmse:0.87708	validation_1-rmse:0.87683
[23]	validation_0-rmse:0.87002	validation_1-rmse:0.87096
[24]	validation_0-rmse:0.86360	validation_1-rmse:0.86514
[25]	validation_0-rmse:0.85670	validation_1-rmse:0.85983
[26]	validation_0-rmse:0.85034	validation_1-rmse:0.85549
[27]	validation_0-rmse:0.84389	validation_1-rmse:0.85008
[28]	validation_0-rmse:0.83716	validation_1-rmse:0.84606
[29]	validation_0-rmse:0.83105	validation_1-rmse:0.83916
[30]	validation_0-rmse:0.82440	validation_1-rmse:0.83227
[31]	validation_0-rmse:0.81801	validation_1-rmse:0.82773
[32]	validation_0-rmse:0.81151	validation_1-rmse:0.82178
[33]	validation_0-rmse:0.80532	validation_1-rmse:0.81746
[34]	validation_0-rmse:0.79955	validation_1-rmse:0.81196
[35]	validation_0-rmse:0.79352	validation_1-rmse:0.80754
[36]	validation_0-rmse:0.78750	validation_1-rmse:0.80339
[37]	validation_0-rmse:0.78148	validation_1-rmse:0.79921
[38]	validation_0-rmse:0.77570	validation_1-rmse:0.79367
[39]	validation_0-rmse:0.76967	validation_1-rmse:0.78925
[40]	validation_0-rmse:0.76375	validation_1-rmse:0.78643
[41]	validation_0-rmse:0.75804	validation_1-rmse:0.78255
[42]	validation_0-rmse:0.75225	validation_1-rmse:0.77777
[43]	validation_0-rmse:0.74650	validation_1-rmse:0.77164
[44]	validation_0-rmse:0.74076	validation_1-rmse:0.76706
[45]	validation_0-rmse:0.73533	validation_1-rmse:0.76232
[46]	validation_0-rmse:0.72947	validation_1-rmse:0.75839
[47]	validation_0-rmse:0.72429	validation_1-rmse:0.75415
[48]	validation_0-rmse:0.71854	validation_1-rmse:0.75056
[49]	validation_0-rmse:0.71317	validation_1-rmse:0.74592
[50]	validation_0-rmse:0.70746	validation_1-rmse:0.74222
[51]	validation_0-rmse:0.70184	validation_1-rmse:0.73833
[52]	validation_0-rmse:0.69649	validation_1-rmse:0.73426
[53]	validation_0-rmse:0.69116	validation_1-rmse:0.73101
[54]	validation_0-rmse:0.68566	validation_1-rmse:0.72658
[55]	validation_0-rmse:0.68037	validation_1-rmse:0.72325
[56]	validation_0-rmse:0.67513	validation_1-rmse:0.72002
[57]	validation_0-rmse:0.66994	validation_1-rmse:0.71644
[58]	validation_0-rmse:0.66493	validation_1-rmse:0.71210
[59]	validation_0-rmse:0.66011	validation_1-rmse:0.70894
[60]	validation_0-rmse:0.65525	validation_1-rmse:0.70607
[61]	validation_0-rmse:0.65025	validation_1-rmse:0.70332
[62]	validation_0-rmse:0.64552	validation_1-rmse:0.69977
[63]	validation_0-rmse:0.64087	validation_1-rmse:0.69592
[64]	validation_0-rmse:0.63625	validation_1-rmse:0.69246
[65]	validation_0-rmse:0.63172	validation_1-rmse:0.68889
[66]	validation_0-rmse:0.62670	validation_1-rmse:0.68502
[67]	validation_0-rmse:0.62191	validation_1-rmse:0.68215
[68]	validation_0-rmse:0.61757	validation_1-rmse:0.68001
[69]	validation_0-rmse:0.61292	validation_1-rmse:0.67593
[70]	validation_0-rmse:0.60816	validation_1-rmse:0.67357
[71]	validation_0-rmse:0.60359	validation_1-rmse:0.67027
[72]	validation_0-rmse:0.59921	validation_1-rmse:0.66659
[73]	validation_0-rmse:0.59481	validation_1-rmse:0.66447
[74]	validation_0-rmse:0.59053	validation_1-rmse:0.66122
[75]	validation_0-rmse:0.58626	validation_1-rmse:0.65870
[76]	validation_0-rmse:0.58218	validation_1-rmse:0.65660
[77]	validation_0-rmse:0.57779	validation_1-rmse:0.65320
[78]	validation_0-rmse:0.57372	validation_1-rmse:0.65074
[79]	validation_0-rmse:0.56971	validation_1-rmse:0.64906
[80]	validation_0-rmse:0.56563	validation_1-rmse:0.64689
[81]	validation_0-rmse:0.56156	validation_1-rmse:0.64422
[82]	validation_0-rmse:0.55748	validation_1-rmse:0.64229
[83]	validation_0-rmse:0.55351	validation_1-rmse:0.64003
[84]	validation_0-rmse:0.54923	validation_1-rmse:0.63742
[85]	validation_0-rmse:0.54530	validation_1-rmse:0.63462
[86]	validation_0-rmse:0.54139	validation_1-rmse:0.63189
[87]	validation_0-rmse:0.53756	validation_1-rmse:0.62851
[88]	validation_0-rmse:0.53350	validation_1-rmse:0.62619
[89]	validation_0-rmse:0.52988	validation_1-rmse:0.62422
[90]	validation_0-rmse:0.52593	validation_1-rmse:0.62078
[91]	validation_0-rmse:0.52208	validation_1-rmse:0.61873
[92]	validation_0-rmse:0.51849	validation_1-rmse:0.61777
[93]	validation_0-rmse:0.51458	validation_1-rmse:0.61524
[94]	validation_0-rmse:0.51082	validation_1-rmse:0.61359
[95]	validation_0-rmse:0.50701	validation_1-rmse:0.61151
[96]	validation_0-rmse:0.50340	validation_1-rmse:0.60991
[97]	validation_0-rmse:0.49976	validation_1-rmse:0.60728
[98]	validation_0-rmse:0.49607	validation_1-rmse:0.60516
[99]	validation_0-rmse:0.49264	validation_1-rmse:0.60347

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [99]:

for i in range(5):
    print(test_dataset[i])

{'input_ids': tensor([  101,  2026,  7570, 27982,  2024,  2652,  4533,  2138,  1045,  2572,
         1037,  4368,  2100,  2711,  2029,  2064,  2022,  2437,  2026,  2568,
         2514,  2104,  2202,  5165,  2006,  2033,  2029,  2064,  2022,  5094,
         2005,  1996,  3778,  8304,  1012,  2026,  7570, 27982,  2065,  2057,
         2024,  2652,  4533,  1010,  2026,  2568,  2003,  4208,  2006,  2055,
         1996,  2208,  1010,  2129,  2000,  2663,  2130,  2130,  3279,  2041,
        26176,  1996,  2208,  1012,   102,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]), 'labels': tensor(0.)}
{'input_ids': tensor([  101,  2026,  5440,  2173,  2003,  1999, 14065, 11687,  9953,  1012,
         2009,  2003,  1999, 25157,  7716,  6553,  1012,  2009,  2003,  1996,
         3379,  1997,  5185,  2935,  3158,  4570, 18663,  2527, 20087,  1012,
         2009,  2038,  2698,  4564,  2000,  3942,  1996,  3379,  1012,  2009,
         2003,  1037,  2204,  2173,  2000,  4374,  1996, 14841,  6824,  7911,
         1012,  2005,  2634,  2182,  1010, 12783,  1997,  2111,  2000,  3942,
         1996,  2935,  3158,  4570, 18663,  2527, 20087,  1010,  1999, 14841,
         6824,  7911,  2031,  1037,  2843,  1997,  3182,  2000,  3942,  1996,
         7538,  1012,  1999, 14841,  6824,  7911,  1010,  1996,  2935,  2003,
         2200,  3297,  1012,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]), 'labels': tensor(0.)}
{'input_ids': tensor([  101,  3398,  1010,  2026,  2190,  2420,  1999,  2026,  2166,  2003,
         3728,  1045,  2288,  2019,  2400,  1999,  2019,  3834,  2095,  2644,
         4842,  1012,  1010,  1996,  2420,  2024,  2200,  2367,  1999,  2026,
         2166,  2138,  1997,  3588,  2420,  2024,  2200,  2691,  2420,  2005,
         2033,  1012,  2296,  2154,  1045,  3218,  2005,  1996,  2400,  1998,
         2893,  2204,  6017,  1999,  2026,  5739,  1012,  1010,  1996,  2420,
         2024,  2200,  3407,  2138,  1997,  1045,  5632,  2007,  2026,  3008,
         1998,  2026,  3566,  1998,  8600,  1999,  2008,  7905, 11444,  3351,
         2241, 12546,  1012,  3398,  1010,  1996,  2154,  2003,  2200,  2569,
         1998,  1045,  2514,  2200,  3407,  2138,  1997,  3588,  2420,  2024,
         2691,  1998,  1996,  2420,  2081,  2033,  3407,  1998,  2026,  2111,
         1010,  2026,  2155,  2111,  2036,  2514,  2200,  3407,  1998,  2060,
         2111,  2036,  2514,  2200,  3407,  1012,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]), 'labels': tensor(0.)}
{'input_ids': tensor([  101,  2941,  1996,  2087,  1045,  2224,  2009,  2000,  5959,  2003,
        12560, 16861,  1012,  1045,  2428,  1996, 16861,  2138,  2017,  2323,
         2224,  2070,  2172,  7023,  1999,  2017,  2017,  2064,  2079,  2009,
         1998,  2017,  2064,  2022,  2583,  2000,  2228,  1998,  2224,  1996,
         3437,  1998,  2507,  1037,  5576,  1999,  1037,  3677,  6413,  2126,
         1012,  2204,  2518,  2003,  2026,  2190, 17792,  2003,  2000,  5247,
         2172,  3815,  1997,  2051,  2006,  2008,  2044,  2183,  2000,  2267,
         2030,  2087,  1997,  1996,  2051,  1045,  5247,  2006, 16861,  1012,
         2009,  2003,  2026,  5221,  8404,  2138,  1996, 16861,  2003,  2428,
         2590,  2005,  1996, 11073,  1998,  2673,  1012,  1045,  2428,  2009,
         2172,  1012,  3398,  1045,  2202,  2070,  2393,  2013,  1996,  2013,
         2026,  2814,  2004,  2004, 10779,  2015,  2008,  3957,  2033,  2438,
         7023,  2000,  3857,  2062, 14727,  1998,  2062,  5875,  2138,  2057,
         2064,  2175,  2488,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]), 'labels': tensor(0.)}
{'input_ids': tensor([  101,  1045,  2052,  2000,  2468,  1037,  5053,  3131,  1012,  2426,
         1996,  2396,  1999,  1996,  2088,  1010,  1045,  2227,  2017,  1012,
         1045,  2052,  2000,  6162,  2026,  3125,  1999, 13729,  2023,  1012,
         2151,  8190,  1996, 13869,  1998,  2151,  4807,  3471,  4385,  1012,
         9587, 29068,  8520,  2013,  2969,  1011, 12774, 11360,  1010,  4385,
         1012, 12774,  6876,  2024,  2467,  3666,  2070,  5691,  1010,  4385,
         1012,  1045,  2052,  2000,  2079,  2396,  2573,  2011,  3752,  2808,
         1010,  7639, 25464,  2015,  1010,  2030,  2011,  4083,  2000,  3443,
         2070, 15902,  2051,  1012,  1045,  2052,  2000,  6162,  3289,  2011,
         2551,  1999,  1996,  2291,  1012,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]), 'labels': tensor(0.)}

In [131]:
test_audio_folder= "/kaggle/working/processed_audio/test"     # Audio_test embeddings.

audio_embeddings_test = []

for fname in test_df['filename']:
    audio_path = os.path.join(test_audio_folder, fname)
    emb = extract_audio_embedding(audio_path, wav2vec_model, wav2vec_processor, device)
    audio_embeddings_test.append(emb)

In [132]:
audio_embeddings_test = np.vstack(audio_embeddings_test)


audio_embeddings_test.shape

(204, 768)

In [133]:
X_test = np.concatenate([test_bert_embeds, audio_embeddings_test], axis=1)  #Test Concatenated embeddings




Y_pred= xgb_model.predict(X_test)



submission = pd.DataFrame({
    "filename":  test_df["filename"],  
    "label": Y_pred             
})

submission.to_csv("submission.csv", index=False)
print(submission.head())
print("submission.csv saved with correct column order.")

         filename     label
0   audio_804.wav  3.183584
1  audio_1028.wav  2.911405
2   audio_865.wav  3.042996
3   audio_774.wav  3.511645
4  audio_1138.wav  3.030894
submission.csv saved with correct column order.

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [07:42:29] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [07:42:29] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)